version: '3'
networks:

  backend:
    driver: bridge

services:

  ### Mysql ###########################################
  mysql:
    image: mysql:latest
    volumes:
      - "../data/db:/var/lib/mysql"
    container_name: dzemo-demo-mysql
    hostname: dzemo-demo-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=lending_and_repayment
      - MYSQL_USER=lending_and_repayment
      - MYSQL_PASSWORD=12345678

  ### SFTP #############################################
  sftp:
    image: atmoz/sftp
    container_name: dzemo-demo-sftp
    hostname: dzemo-demo-sftp
    ports:
      - "2222:22"
    networks:
      - backend
    volumes:
      - "../data/sftp:/home/lending-and-repayment-service/upload"
    command: lending-and-repayment-service:12345678:1001
