version: '3'
networks:

  backend:
    driver: bridge

services:

  ### Mysql ###########################################
  mysql:
    image: mysql:latest
    volumes:
      - "../data/db:/var/lib/mysql"
    container_name: dzemo-demo-mysql
    hostname: dzemo-demo-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=elevator_manager
      - MYSQL_USER=elevator_manager
      - MYSQL_PASSWORD=12345678

  ### Redis #############################################
  redis:
    build: ./redis
    restart: always
    image: dzemo-demo-redis
    container_name: dzemo-demo-redis
    hostname: dzemo-demo-redis
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - "../data/redis:/data"

 ### RabbitMQ #############################################
  rabbitmq:
    build: ./rabbitmq
    restart: always
    image: dzemo-demo-mq
    container_name: dzemo-demo-mq
    hostname: dzemo-demo-mq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15671:15671"
    privileged: true
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - backend